apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
data:
  server.conf: |
    server {
        listen 8081 default_server;
        listen [::]:8081 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        server_name _;

        location /google {
                return      301 https://google.com;
        }

        location / {
                try_files $uri $uri/ =404;
        }

        location /photo {
                index photo.html;
        }

        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/run/php-fpm.sock;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param SCRIPT_NAME $fastcgi_script_name;
                fastcgi_index index.php;
                include fastcgi_params;
        }

        location /music {
                index music.html;
        }
    }
